version: "3"

services:
    app:
        build:
            context: .
        ports:
            - "8000:8000"
        volumes:
            - ./project:/project
        command: >
          sh -c "python manage.py runserver 0.0.0.0:8000"
        env_file:
            -   ./.env.dev
    db:
        image: postgres:12.0-alpine
        volumes:
        -   postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=coolpam
            - POSTGRES_PASSWORD=coolpam
            - POSTGRES_DB=coolpam_dev

volumes:
    postgres_data:



