# Generated by Django 2.1.5 on 2021-08-18 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitCharge',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='unitcharge', serialize=False, to='core.Customer')),
                ('created', models.DateTimeField(auto_now=True)),
                ('charge', models.FloatField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'UnitCharge',
                'verbose_name_plural': 'UnitCharges',
            },
        ),
    ]
