# Generated by Django 2.1.5 on 2021-08-19 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210818_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitcharge',
            old_name='customer',
            new_name='user',
        ),
    ]
