# Generated by Django 2.1.5 on 2021-08-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_meterreading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='consumption',
            field=models.FloatField(blank=True, editable=False),
        ),
    ]
