# Generated by Django 2.1.5 on 2021-08-19 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210819_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='consumption',
            field=models.FloatField(max_length=14),
        ),
    ]
