# Generated by Django 2.1.5 on 2021-08-19 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210819_1621'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meterreading',
            old_name='current_reading',
            new_name='meter_reading',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='consumption',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='previous_reading',
        ),
    ]
